name: retrofit_generator
description: retrofit generator is an dio client generator using source_gen and inspired by Chopper and Retrofit.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0-beta4
  source_gen: ^0.9.4+2
  built_collection: ^5.0.0
  code_builder: ^3.2.0
  tuple: ^2.0.0-nullsafety.0
  retrofit:
    path: ../annotation
  analyzer: ^1.1.0
  dart_style: ^1.0.0
  build: ^1.6.3

dev_dependencies:
  test:
  source_gen_test: any
  resource:
